name: tfg_env
channels:
  - conda-forge 
  - defaults
dependencies:
  - python=3.12.8 
  - numpy
  - pandas
  - matplotlib
  - jupyterlab
  - scikit-learn
  - openpyxl
  - pip
  - pip:
      - tensorflow 
